# .devcontainer/Dockerfile
FROM mcr.microsoft.com/devcontainers/java:17

# Instalar gradle, si lo deseas (ya viene con Gradle en muchos casos)
# RUN apt-get update && apt-get install -y gradle

# Variables de entorno, etc.
ENV FINERACT_HIKARI_PASSWORD=mysql
ENV FINERACT_HIKARI_USERNAME=root

# Cualquier otra instalación adicional que requieras
# RUN apt-get install -y <otras herramientas>
